apiVersion: guni.dev/v1
kind: Minecraft
metadata:
  name: guni-world
spec:
  image: itzg/minecraft-server:java17-graalvm-ce
  server:
    motd: guni-world
    gameMode: Survival
    env:
    - name: EULA
      value: "TRUE"
    - name: VERSION
      value: "1.20.4"
    - name: WHITELIST
      value: "guni1192"
  storage:
    size: "2Gi"
    storageClassName: "standard"
    mountPath: "/data"
