apiVersion: guni.dev/v1
kind: Minecraft
metadata:
  name: guni-world
spec:
  image: itzg/minecraft-server:java17-graalvm-ce
  server:
    motd: guni-world
    gamemode: Survival
  storage:
    size: "2Gi"
    storageClassName: "standard"
    mountPath: "/data"
