name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - run: sudo apt-get update && sudo apt-get install -y make curl

      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  check-crd:
    runs-on: ubuntu-latest
    needs: [clippy]
    steps:
      - uses: actions/checkout@v3

      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v2.36.2

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - name: Install Kubernetes CLI tools
        run: aqua install

      - uses: Swatinem/rust-cache@v2

      - run: sudo apt-get update && sudo apt-get install -y make curl

      - name: Create kind cluster
        run: make create-cluster

      - name: Build container image and load to kind cluster
        run: make build

      - name: show kubernetes info
        run: kubectl version -o yaml

      - name: Install minecraft-operator CRDs
        run: make install

      - name: Deploy minecraft-operator and example CR
        run: make deploy
